// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPiLRnkSu5iskyYEpPEIL6AwWbqGl7fjQ',
    appId: '1:526361535582:web:a7c583ecca0b5e652300cf',
    messagingSenderId: '526361535582',
    projectId: 'cookflow-d5d3d',
    authDomain: 'cookflow-d5d3d.firebaseapp.com',
    storageBucket: 'cookflow-d5d3d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6Q6ghD_YcwEzQxhD_uX4-XXZ3Kc3HGJw',
    appId: '1:526361535582:android:d3dcb199e9e9118b2300cf',
    messagingSenderId: '526361535582',
    projectId: 'cookflow-d5d3d',
    storageBucket: 'cookflow-d5d3d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA88xqH_5tBZYtxIRm6w-dsBE7SRyFpAQ8',
    appId: '1:526361535582:ios:362b84159a1490802300cf',
    messagingSenderId: '526361535582',
    projectId: 'cookflow-d5d3d',
    storageBucket: 'cookflow-d5d3d.firebasestorage.app',
    iosBundleId: 'com.example.cookflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA88xqH_5tBZYtxIRm6w-dsBE7SRyFpAQ8',
    appId: '1:526361535582:ios:362b84159a1490802300cf',
    messagingSenderId: '526361535582',
    projectId: 'cookflow-d5d3d',
    storageBucket: 'cookflow-d5d3d.firebasestorage.app',
    iosBundleId: 'com.example.cookflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPiLRnkSu5iskyYEpPEIL6AwWbqGl7fjQ',
    appId: '1:526361535582:web:e9aebfa533e25ceb2300cf',
    messagingSenderId: '526361535582',
    projectId: 'cookflow-d5d3d',
    authDomain: 'cookflow-d5d3d.firebaseapp.com',
    storageBucket: 'cookflow-d5d3d.firebasestorage.app',
  );

}